import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import PrelineScriptWrapper from '@/components/PrelineScriptWrapper';

const poppins = Poppins({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <Header />
                <main className="min-h-[80vh]">
                    {children}
                </main>
                <Footer />
                <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js"></script>
                <script src="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro@3.0.5/index.min.js"></script>
            </body>
            <PrelineScriptWrapper />
        </html>
    );
}
